[package]
name = "journal-inbox-muse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
journal-inbox-worker = { path = "../journal-inbox-worker" }
journal-runtime-muse = { path = "../journal-runtime-muse" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "journal-inbox-muse"
path = "src/main.rs"

[lints]
workspace = true
