[package]
name = "journal-adapter-hermes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
journal-adapter-core = { path = "../journal-adapter-core" }
journal-adapter-spool = { path = "../journal-adapter-spool" }
journal-client = { path = "../journal-client" }
journal-runtime-hermes = { path = "../journal-runtime-hermes" }
serde_json.workspace = true
tokio.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "journal-adapter-hermes"
path = "src/main.rs"

[lints]
workspace = true
