[package]
name = "journal-adapter-spool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
journal-adapter-core = { path = "../journal-adapter-core" }
fs2.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
