[package]
name = "aj-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "aj-admin"
path = "src/main.rs"

[dependencies]
journal-client = { path = "../journal-client" }
serde_json.workspace = true

[lints]
workspace = true
